### ISSUE TITLE
android app fails to start

### ISSUE THREAD

**Issue by drapanjanas** [alwx/luno-react-native#5]
```
$ lein prod-build
$ react-native run-android
```

Results in:
<img width="600" alt="screen shot 2016-01-30 at 13 30 11" src="https://cloud.githubusercontent.com/assets/1648448/12695681/fa4f170e-c755-11e5-9c67-fbe68141c22f.png">

I think the problem caused by requiring platform specific namespaces from shared namespace: https://github.com/alwx/luno-react-native/blob/master/src/luno/shared/scenes/about.cljs#L6-L7

When I remove these requires (and github button) application works fine.

**Comment by alwx** [comment]
Fixed it.

But let me explain why I solved this issue that way :)
I don't like the idea of using :platform in code. We don't actually need **shared** components to know about type of OS on a specific device. That's why I think that the best way to solve this issue is to supply github-button-fn to about-scene component. It keeps shared components independent and makes it easier to reuse these components.

**Comment by drapanjanas** [comment]
Works fine now, thanks!
